'use client';
import Link from 'next/link';
import { BookOpen, FileText, Search, Sparkles, Plus, ArrowUpRight, BarChart3 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
type Note={id:string;title:string;subject:string|null;content:string;updatedAt:string;studyResults:{operation:string}[]};
export default function DashboardPage(){
 const [notes,setNotes]=useState<Note[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const res=await fetch('/api/notes'+(query?`?q=${encodeURIComponent(query)}`:''));const json=await res.json();if(json.success)setNotes(json.data);setLoading(false)}
 useEffect(()=>{load()},[query]);
 const stats=useMemo(()=>({notes:notes.length,generations:notes.reduce((a,n)=>a+n.studyResults.length,0),cards:notes.reduce((a,n)=>a+n.studyResults.filter(r=>r.operation==='flashcards').length,0)}),[notes]);
 return <main><header style={{borderBottom:'1px solid #e5e7eb',background:'#fff'}}><div className="container" style={{height:74,display:'flex',alignItems:'center',justifyContent:'space-between',gap:18}}><Link href="/" style={{fontWeight:900,fontSize:19,textDecoration:'none',color:'inherit'}}>StudyFlow<span style={{color:'#315efb'}}> AI</span></Link><div style={{display:'flex',gap:10,alignItems:'center'}}><div style={{position:'relative'}}><Search size={17} color="#98a2b3" style={{position:'absolute',left:12,top:13}}/><input aria-label="Search notes" className="input" style={{width:270,paddingLeft:38}} placeholder="Search notes…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Link href="/notes/new" className="btn btn-primary"><Plus size={17}/> New note</Link></div></div></header>
 <div className="container" style={{padding:'40px 0 70px'}}><div style={{marginBottom:24}}><div className="badge"><BookOpen size={13}/> Study workspace</div><h1 style={{fontSize:38,letterSpacing:'-.035em',margin:'12px 0 5px'}}>Good to see you.</h1><p style={{color:'#667085',margin:0}}>Turn your notes into material you can actually revise.</p></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:14,marginBottom:28}}><Stat label="Total notes" value={stats.notes}><FileText size={18}/></Stat><Stat label="AI generations" value={stats.generations}><Sparkles size={18}/></Stat><Stat label="Flashcard sets" value={stats.cards}><BarChart3 size={18}/></Stat></div>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><h2 style={{fontSize:21,margin:0}}>Recent notes</h2>{notes.length>0&&<span style={{fontSize:13,color:'#667085'}}>{notes.length} saved</span>}</div>
 {loading?<div className="card" style={{padding:30,color:'#667085'}}>Loading your study space…</div>:notes.length===0?<div className="card" style={{padding:46,textAlign:'center'}}><div style={{width:52,height:52,display:'grid',placeItems:'center',background:'#eef3ff',borderRadius:15,margin:'0 auto 15px',color:'#315efb'}}><FileText/></div><h3 style={{margin:'0 0 7px'}}>Your study workspace is empty.</h3><p style={{color:'#667085',maxWidth:520,margin:'0 auto 18px',lineHeight:1.6}}>Create your first note and turn it into a summary, key points, or flashcards.</p><Link href="/notes/new" className="btn btn-primary">Create your first note</Link></div>:<div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:14}}>{notes.map(n=><Link key={n.id} href={`/notes/${n.id}`} className="card" style={{padding:20,textDecoration:'none',color:'inherit',display:'block'}}><div style={{display:'flex',justifyContent:'space-between',gap:15}}><div><div style={{fontWeight:850,fontSize:17}}>{n.title}</div><div style={{fontSize:12,color:'#667085',marginTop:4}}>{n.subject||'General study'} · {new Date(n.updatedAt).toLocaleDateString()}</div></div><ArrowUpRight size={18} color="#98a2b3"/></div><p style={{color:'#667085',lineHeight:1.55,fontSize:13,margin:'15px 0 0'}}>{n.content.slice(0,150)}{n.content.length>150?'…':''}</p><div style={{display:'flex',gap:7,marginTop:15}}>{n.studyResults.slice(0,2).map((r,i)=><span className="badge" key={i}>{r.operation.replace('-', ' ')}</span>)}</div></Link>)}</div>}
 </div></main>;
}
function Stat({label,value,children}:{label:string;value:number;children:React.ReactNode}){return <div className="card" style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:13,color:'#667085',fontWeight:700}}>{label}</span><span style={{color:'#315efb'}}>{children}</span></div><div style={{fontSize:30,fontWeight:900,marginTop:13}}>{value}</div></div>}
